
name: Run Add-On
on: repository_dispatch



jobs:
  Run-Add-On:
    uses: MuckRock/documentcloud-addon-workflows/.github/workflows/run-addon.yml@fix-quote
    with:
      timeout: 360
    secrets:
      token: ${{ secrets.API_KEY }}
